In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sqlite3

**FULL ANALYSIS AND VISUALIZATIONS CAN BE FOUND HERE**
<a>(https://daeshawn.ca/#/posts/abs-challenge-analysis)</a>

In [10]:
# Create the database connection and cursor
conn = sqlite3.connect('../data/processed/abs_challenge.db')
cursor = conn.cursor()

In [14]:
splits_query = """
SELECT
COUNT(*) as total_challenges,
(SELECT COUNT(*) FROM batter_challenge_results WHERE description = 'called_strike') * 1.0 / (SELECT COUNT(*) FROM batter_challenge_results) * 100 as confirmed_pct,
(SELECT COUNT(*) FROM batter_challenge_results WHERE description = 'ball') * 1.0 / (SELECT COUNT(*) FROM batter_challenge_results) * 100 as overturned_pct
FROM batter_challenge_results;
"""



splits_df = pd.read_sql_query(splits_query, conn)
splits_df.head()

   total_challenges  confirmed_pct  overturned_pct
0              2105      52.874109       47.125891

BATTER CHALLENGE VALUE LEADERS

In [20]:
challenge_value_leaders_query = """
SELECT
player_name,
SUM(challenge_value) as total_challenge_value,
COUNT(*) as total_challenges,
COUNT(CASE WHEN description = 'ball' THEN 1 END) as total_overturned
FROM batter_challenge_results
WHERE challenge_value IS NOT NULL
GROUP BY player_name
ORDER BY total_challenge_value DESC;
"""

challenge_value_leaders_df = pd.read_sql_query(challenge_value_leaders_query, conn)
challenge_value_leaders_df.head(20)

,player_name,total_challenge_value,total_challenges,total_overturned
0,"Stewart, Sal",17.495,30,20
1,"McGonigle, Kevin",12.764,17,12
2,"Schneider, Davis",9.741,12,9
3,"Abrams, CJ",9.557,7,7
4,"Reynolds, Bryan",9.188,14,8
5,"Bogaerts, Xander",9.062,13,9
6,"Kurtz, Nick",8.553,9,7
7,"Paredes, Isaac",8.305,6,6
8,"Caballero, José",8.210,17,10
9,"Garcia, Maikel",8.154,17,10
10,"Altuve, Jose",8.034,15,10
11,"Schwarber, Kyle",7.998,14,9
12,"Herrera, Iván",7.882,15,9
13,"Rooker, Brent",7.652,10,7
14,"Bell, Josh",6.685,12,8
15,"Judge, Aaron",6.546,8,6
16,"Hernández, Teoscar",6.521,10,7
17,"Rocchio, Brayan",6.472,11,7
18,"Eldridge, Bryce",6.356,5,5
19,"Trout, Mike",6.311,8,5

LEADERS IN AVERAGE CHALLENGE VALUE PER CHALLENGE (HITTERS)

In [17]:
average_challenge_value_leaders_query = """
SELECT
    player_name,
    AVG(challenge_value) AS average_challenge_value
FROM batter_challenge_results
WHERE challenge_value IS NOT NULL
GROUP BY player_name
HAVING COUNT(*) >= 5
ORDER BY average_challenge_value DESC;
"""

average_challenge_value_leaders_df = pd.read_sql_query(average_challenge_value_leaders_query, conn)
average_challenge_value_leaders_df.head(20)

         player_name  average_challenge_value
0     Paredes, Isaac                 1.384167
1         Abrams, CJ                 1.365286
2    Eldridge, Bryce                 1.271200
3      Gilbert, Drew                 1.127800
4     Cowser, Colton                 0.967400
5        Kurtz, Nick                 0.950333
6      Caissie, Owen                 0.930167
7    Carroll, Corbin                 0.889000
8     Taveras, Leody                 0.851000
9        Lopez, Otto                 0.833000
10      Judge, Aaron                 0.818250
11  Schneider, Davis                 0.811750
12     Lee, Jung Hoo                 0.801167
13     McMahon, Ryan                 0.793000
14       Trout, Mike                 0.788875
15     Abreu, Wilyer                 0.766800
16     Rooker, Brent                 0.765200
17  McGonigle, Kevin                 0.750824
18     Gray, Tristan                 0.730800
19    Burleson, Alec                 0.713167

In [21]:
splits_query = """
SELECT
COUNT(*) as total_challenges,
(SELECT COUNT(*) FROM catcher_challenge_results WHERE description = 'ball') * 1.0 / (SELECT COUNT(*) FROM catcher_challenge_results) * 100 as confirmed_pct,
(SELECT COUNT(*) FROM catcher_challenge_results WHERE description = 'called_strike') * 1.0 / (SELECT COUNT(*) FROM catcher_challenge_results) * 100 as overturned_pct
FROM catcher_challenge_results;
"""



splits_df = pd.read_sql_query(splits_query, conn)
splits_df.head()

   total_challenges  confirmed_pct  overturned_pct
0              2342      40.734415       59.265585

LEADERS IN TOTAL CHALLENGE VALUE (CATCHERS)

In [23]:
catcher_challenge_value_leaders_query = """
SELECT
player_name,
SUM(challenge_value) as total_challenge_value,
COUNT(*) as total_challenges,
COUNT(CASE WHEN description = 'ball' THEN 1 END) as total_overturned
FROM catcher_challenge_results
WHERE challenge_value IS NOT NULL
GROUP BY player_name
ORDER BY total_challenge_value DESC;
"""

catcher_challenge_value_leaders_df = pd.read_sql_query(catcher_challenge_value_leaders_query, conn)
catcher_challenge_value_leaders_df.head(20)

,player_name,total_challenge_value,total_challenges,total_overturned
0,"Stephenson, Tyler",40.901,59,17
1,"Contreras, William",38.859,90,38
2,"Perez, Salvador",35.667,50,14
3,"Langeliers, Shea",34.449,61,25
4,"Goodman, Hunter",34.147,55,20
5,"Kelly, Carson",32.007,34,6
6,"Dingler, Dillon",31.944,49,15
7,"Caratini, Victor",31.921,52,17
8,"Wells, Austin",27.624,48,18
9,"O'Hoppe, Logan",27.398,57,23
10,"Realmuto, J.T.",26.658,30,6
11,"Pagés, Pedro",26.647,36,11
12,"Smith, Will",26.388,47,16
13,"Fortes, Nick",25.689,60,24
14,"Baldwin, Drake",23.334,27,7
15,"Jeffers, Ryan",22.255,36,14
16,"Fermin, Freddy",21.643,41,18
17,"Bailey, Patrick",21.643,56,24
18,"Amaya, Miguel",20.929,35,12
19,"Garver, Mitch",19.908,24,5

LEADERS IN AVERAGE CHALLENGE VALUE PER CHALLENGE (CATCHERS)

In [25]:
average_challenge_value_leaders_query = """
SELECT
    player_name,
    AVG(challenge_value) AS average_challenge_value
FROM catcher_challenge_results
WHERE challenge_value IS NOT NULL
GROUP BY catcher_id
HAVING COUNT(*) >= 5
ORDER BY average_challenge_value DESC;
"""

average_challenge_value_leaders_df = pd.read_sql_query(average_challenge_value_leaders_query, conn)
average_challenge_value_leaders_df.head(20)

             player_name  average_challenge_value
0   Del Castillo, Adrian                 0.974375
1         Durán, Rodolfo                 0.956083
2          Kelly, Carson                 0.941382
3         Realmuto, J.T.                 0.888600
4          Higgins, P.J.                 0.883909
5         Baldwin, Drake                 0.864222
6            León, Sandy                 0.846950
7          Garver, Mitch                 0.829500
8         Gasper, Mickey                 0.790250
9       d'Arnaud, Travis                 0.786100
10         Jansen, Danny                 0.761500
11          Pagés, Pedro                 0.740194
12          Wong, Connor                 0.725727
13       Perez, Salvador                 0.713340
14          Rogers, Jake                 0.693889
15     Stephenson, Tyler                 0.693237
16         Herrera, Iván                 0.680370
17       Dingler, Dillon                 0.651918
18       Moreno, Gabriel                 0.625207
19       Goodman, Hunter                 0.620855

In [32]:
# Find the rank of Valenzuela, Brandon in the average_challenge_value_leaders_df
rank = average_challenge_value_leaders_df[average_challenge_value_leaders_df['player_name'] == 'Valenzuela, Brandon'].index[0] + 1
print(f"Valenzuela, Brandon's rank: {rank}")

Valenzuela, Brandon's rank: 70

In [34]:
conn.close()